### ISSUE TITLE
bug: onebotV11 上报数据的字段类型有误

### ISSUE THREAD

**Issue by xiaomujin** [lc-cn/onebots#28]
onebot协议V11
使用ws正向连接到机器人后，接收群消息上报数据得到了如下数据
{ "post_type": "message", "message_id": "H6oYlHh+63gAAXkXCGrChWSDAE0B", "user_id": "2021583736", "time": 1686306893, "seq": 96535, "rand": 141214341, "font": "微软雅黑", "message": "test", "raw_message": "test", "message_type": "group", "sender": { "user_id": 2021583736, "nickname": "咕咕咕", "card": "", "sex": "unknown", "age": 0, "area": "", "level": 1, "role": "owner", "title": "" }, "group_id": "531241100", "group_name": "交流群", "block": false, "sub_type": "normal", "anonymous": null, "atme": false, "atall": false, "group": {}, "member": {}, "self_id": 1667047824 }
其中 message_id 和 font 为字符串类型
按onebotV11标准[群消息](https://github.com/botuniverse/onebot-11/blob/master/event/message.md#%E7%BE%A4%E6%B6%88%E6%81%AF)应当都为int类型，望修复

**Comment by lc-cn** [comment]
[以修复于](https://github.com/lc-cn/onebots/commit/65d94ce5ec598bc1d71a266485d00ad063f02c6a)
