### ISSUE TITLE
多个反向ws出现bug

### ISSUE THREAD

**Issue by linya72** [lc-cn/onebots#66]
onebots在设置多个反向ws地址时，会对每个地址建立 设置过的反向地址数量 次的连接
![Cache_709b99409cfcae49.png](https://github.com/lc-cn/onebots/assets/107689301/ade1ff6b-83d3-4220-b19c-df8fba6782b7)

![Cache_-5429aa541cd42404.png](https://github.com/lc-cn/onebots/assets/107689301/789376cc-677d-4891-8c31-409c8eb6aa2a)

![Cache_-443280510409d8da.png](https://github.com/lc-cn/onebots/assets/107689301/17c958c5-6272-4de1-a533-6d0155eec083)

![Cache_2b310f4f6c9f4df7.png](https://github.com/lc-cn/onebots/assets/107689301/3d9d14fa-4f10-4a77-bfc9-c9740ee9e9a5)

**Comment by Well2333** [comment]
经过测试，目前可以确认的是：

1. ws 链接仅存在一个
2. 此链接发生了重复上报的现象
3. 此问题是onebots或icqq导致的，与nonebot2及插件无关

此问题可能的成因是onebots在有多个 `ws_reverse` 连接时，会向其中**每一条连接**发送**链接数量**的事件，而不是正常的向每一条链接发送一个事件。

**Comment by Well2333** [comment]
问题可能是由于对每个 WSR 连接都注册了事件监听器，导致每次事件发生时，每个连接都会收到事件通知。正确的做法应该是无论有多少个连接，每个事件只分发一次。需要检查是不是在每次调用 `startWsReverse` 函数时都重复注册了事件监听器，从而导致同一个事件被多次分发。

相关代码段：
- 配置 WSR 连接的循环：https://github.com/lc-cn/onebots/blob/ff9e047ccb09eb3495d6cbc8881e55da20781b9a/src/service/V11/index.ts#L66
- 注册事件监听器的 `startWsReverse` 函数：https://github.com/lc-cn/onebots/blob/ff9e047ccb09eb3495d6cbc8881e55da20781b9a/src/service/V11/index.ts#L177

**Comment by Misaka-Mikoto-Tech** [comment]
问题的根源在于多次执行 `this.on("dispatch"` 导致的，比如 反向ws

* 初始化多个ws地址
```ts
this.config.ws_reverse.forEach((config) => {
    this.startWsReverse(config) // 对每个wsr地址创建 WebSocket连接
 })
```
* 创建反向ws
```ts
private startWsReverse(url: string) {
        this._createWsr(url)
        this.on("dispatch", (serialized) => { // on() 函数是个 array, 不是 dict, 因此会创建多个回调
            for (const ws of this.wsr) { // 回调内遍历，因此总调用次数变成了 wsr.length * wsr.length
                ws.send(serialized, (err) => {
                    if (err) {
                        this.logger.error(`反向WS(${ws.url})上报事件失败: ` + err.message)
                    } else this.logger.debug(`反向WS(${ws.url})上报事件成功: ` + serialized)
                })
            }
        })
    }
```

**Comment by Gay-GG** [comment]
on为持久监听器，多次调用传入相同的listener，将on改为once即可，创建once监听器接收到事件仅调用一次listener，之后会移除此监听器

**Comment by lc-cn** [comment]
今日修复
