### ISSUE TITLE
一条消息上报两次

### ISSUE THREAD

**Issue by molehzy** [lc-cn/onebots#81]
按照[#局部安装](https://github.com/lc-cn/onebots#%E5%B1%80%E9%83%A8%E5%AE%89%E8%A3%85)配置完后
 
![1](https://raw.githubusercontent.com/molehzy/molehzy.github.io/master/img/issues/onebots/1.png)
![2](https://raw.githubusercontent.com/molehzy/molehzy.github.io/master/img/issues/onebots/2.png)

**Comment by lc-cn** [comment]
已修复
