### ISSUE TITLE
Feature: 希望兼容无 TTY 环境

### ISSUE THREAD

**Issue by BennettChina** [lc-cn/onebots#84]
想在 Docker 等容器环境中使用，而这类环境难以完成 `ticket` 、 短信验证码等用户输入的传输。

参考方案一：

提供类似 `go-cqhttp` 那种网页直接辅助用户获取 `ticket` ，短信验证码可以写个简易网页，给个表单，通过这个表单传递短信验证码，`onebots` 轮询查询 `ticket` 和短信验证码。这又分为统一的域名服务和本地服务两种实现。

参考方案二：

指定文件名，用户可以将 `ticket` 和 短信验证码写入到指定文件中，客户端轮询读取文件内容，当文件内容不为空时即视为用户提交了所需要的参数。

**Comment by lc-cn** [comment]
以实现简单的web界面，用于管理机器人和控制台输入输出
