### ISSUE TITLE
[BUG] V11的getStatus的online字段一直为false，日志有打印登录成功加载好友等信息

### ISSUE THREAD

**Issue by BennettChina** [lc-cn/onebots#86]
onebots：dev分支
icqq: 0.6.6

如题，根据debug测出，`getSelfInfo` 方法返回的 `status` 是 `0`，即 `good` 字段的值，跟判断的`online` 始终无法匹配上，造成一直返回的是 `false`。

**Comment by lc-cn** [comment]
#133 已解决
