### ISSUE TITLE
未找到 <qq号>_v11.jsondb 文件

### ISSUE THREAD

**Issue by RtekiX** [lc-cn/onebots#89]
原gocqhttp + nonebot2 的机器人项目，拟迁移到onebots
运行环境：Windows Server 2012

已使用 npm 安装 icqq 和 onebots 模块，并配置了config文件
使用命令`npx onebots -r icqq`启动项目时，报 **未找到 /根目录/data/<qq号>_v11.jsondb 文件** 错误

文档和issue里没找到解决方法，不太清楚这个文件是怎么生成的

**Comment by lc-cn** [comment]
使用管理员运行，会自动创建才对

**Comment by RtekiX** [comment]
> 使用管理员运行，会自动创建才对

是用管理员运行的。具体报错如图
![image](https://github.com/lc-cn/onebots/assets/40229223/85a32a65-15dc-4714-820e-e24026deab3a)

**Comment by lc-cn** [comment]
你先手动在data目录下创建爱你一个对应的文件，我后续处理这个问题

**Comment by lc-cn** [comment]
内容留空就行

**Comment by RtekiX** [comment]
> 内容留空就行

已解决

**Comment by lc-cn** [comment]
#101
